export interface UserInfo {
  userNo:string;
  name:string;
  email:string;
  thirdPartyLinkApp:string,
  thirdPartyLinkInfo:any,
  pw:string;
  state:Number;
  setInfo:{
    marketing:boolean;
    pushAgree:boolean;
  };
  device:{
    appVer:string;
    osType:string;
    osVer:string;
  };
  token:string;
  inDt:string;
}
